spring.application.name=E-CommerceBackEnd

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ECommerceBackEnd}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql

logging.level.org.hibernate.orm.connections.pooling=off
logging.level.com.zaxxer.hikari=warn

jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.ms=${JWT_EXPIRATION_MS:86400000}

#Java mail sender
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

#TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
