spring.application.name=E-CommerceBackEnd

spring.datasource.url=jdbc:postgresql://localhost:5432/ECommerceBackEnd
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql

logging.level.org.hibernate.orm.connections.pooling=off
logging.level.com.zaxxer.hikari=warn


jwt.secret.key=
jwt.expiration.ms=86400000


#Java mail sender
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

#TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#OAuth2
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=


app.oauth2.redirect-url=http://localhost:3000/oauth2/redirect